// Deterministic slice report generator.
//
// Use this for final handoff / PR metrics instead of hand-writing counts from
// memory. It runs local commands and emits a pasteable markdown block plus a
// machine-readable JSON payload.
//
// Usage:
//   node scripts/slice-report.mjs --slice add-accounts
//   node scripts/slice-report.mjs --slice add-accounts --write
import { existsSync, mkdirSync, readFileSync, writeFileSync } from "node:fs";
import { join } from "node:path";
import { spawnSync } from "node:child_process";

const root = process.cwd();
const args = process.argv.slice(2);
const getArg = (name) => {
  const i = args.indexOf(name);
  return i >= 0 ? args[i + 1] : null;
};
const flags = new Set(args.filter((a) => a.startsWith("--")));
const slice = getArg("--slice") ?? process.env.SLICE ?? "unknown-slice";

function run(command, commandArgs) {
  const r = spawnSync(command, commandArgs, { cwd: root, encoding: "utf8", shell: process.platform === "win32" });
  return { command: [command, ...commandArgs].join(" "), exitCode: r.status ?? 1, output: `${r.stdout || ""}${r.stderr || ""}`.trim() };
}
function readJson(rel) {
  try {
    return JSON.parse(readFileSync(join(root, rel), "utf8"));
  } catch {
    return null;
  }
}
function git(args) {
  const r = run("git", args);
  return r.exitCode === 0 ? r.output : "";
}

const commands = {
  openspecValidate: run("npx", ["openspec", "validate", "--all", "--strict"]),
  openspecList: run("npx", ["openspec", "list"]),
  tests: run("npm", ["run", "test:run"]),
  trace: run("node", ["scripts/check-traceability.mjs", "--check-fresh"]),
  trajectory: run("node", ["scripts/check-trajectory.mjs", "--check-fresh"]),
  evals: run("node", ["scripts/check-eval-ratchet.mjs"]),
  coverage: run("node", ["scripts/check-coverage-ratchet.mjs"]),
};

const openspecPassed = [...commands.openspecValidate.output.matchAll(/^✓\s+/gm)].length;
const activeChanges = /No active changes found/.test(commands.openspecList.output) ? 0 : Math.max(0, (commands.openspecList.output.match(/^\s*\S+/gm) ?? []).length);
const testMatch = commands.tests.output.match(/Tests\s+(\d+)\s+passed/);
const testFilesMatch = commands.tests.output.match(/Test Files\s+(\d+)\s+passed/);
const traceJson = readJson("trace/trace.json");
const trajectoryJson = readJson("trace/trajectory.json");
const evalBaseline = readJson("quality/eval-baseline.json");
const coverageBaseline = readJson("quality/coverage-baseline.json");
const changedFiles = git(["diff", "--name-only", "origin/dev...HEAD"]).split("\n").filter(Boolean);
const log = git(["log", "--format=%H%x00%B%x00END", "origin/dev..HEAD"]);
const trailerCommits = log.split("\u0000END").filter((entry) => entry.includes(`Slice: ${slice}`)).length;
const refs = [...new Set([...log.matchAll(/Refs:\s*([^\n]+)/g)].flatMap((m) => m[1].split(/,\s*/).map((x) => x.trim()).filter(Boolean)))];
const archiveDir = "openspec/changes/archive";
const archivePath = existsSync(join(root, archiveDir))
  ? git(["ls-files", archiveDir]).split("\n").find((f) => f.includes(`-${slice}/review-findings.json`))
  : "";
const reviewFindings = archivePath ? readJson(archivePath) : null;
const rawReviewRefs = Array.isArray(reviewFindings?.rawEvidence) ? reviewFindings.rawEvidence : [];

const result = {
  generatedAt: new Date().toISOString(),
  generatedBy: "scripts/slice-report.mjs",
  slice,
  commands: Object.fromEntries(Object.entries(commands).map(([k, v]) => [k, { command: v.command, exitCode: v.exitCode }])),
  metrics: {
    openspecPassed,
    activeChanges,
    testFilesPassed: Number(testFilesMatch?.[1] ?? 0),
    testsPassed: Number(testMatch?.[1] ?? 0),
    traceFailures: traceJson?.failures?.length ?? null,
    traceWarnings: traceJson?.warnings?.length ?? null,
    trajectoryFailures: trajectoryJson?.failures?.length ?? null,
    trajectoryWarnings: trajectoryJson?.warnings?.length ?? null,
    changedFiles: changedFiles.length,
    evalBaseline,
    coverageBaseline,
    reviewFindings: reviewFindings ? reviewFindings.clean === true ? "clean" : "present-not-clean" : "missing",
    rawReviewEvidenceRefs: rawReviewRefs.length,
    sliceTrailerCommits: trailerCommits,
    refs,
  },
};

const m = result.metrics;
const md = `<!-- slice-report:start -->
### Generated slice report: ${slice}

Generated by \`node scripts/slice-report.mjs --slice ${slice}\` at ${result.generatedAt}. Do not hand-write these metrics.

| Metric | Value |
|---|---:|
| OpenSpec validated specs | ${m.openspecPassed} |
| Active OpenSpec changes | ${m.activeChanges} |
| Test files / tests passed | ${m.testFilesPassed} / ${m.testsPassed} |
| Trace failures / warnings | ${m.traceFailures ?? "n/a"} / ${m.traceWarnings ?? "n/a"} |
| Trajectory failures / warnings | ${m.trajectoryFailures ?? "n/a"} / ${m.trajectoryWarnings ?? "n/a"} |
| Changed files vs origin/dev | ${m.changedFiles} |
| Review findings | ${m.reviewFindings} |
| Raw review evidence refs | ${m.rawReviewEvidenceRefs} |
| Slice trailer commits | ${m.sliceTrailerCommits} |
| Refs | ${m.refs.length ? m.refs.join(", ") : "-"} |

Command exits: ${Object.entries(result.commands).map(([name, c]) => `${name}=${c.exitCode}`).join(", ")}.
<!-- slice-report:end -->`;

if (flags.has("--write")) {
  mkdirSync(join(root, "docs", "qa"), { recursive: true });
  mkdirSync(join(root, "trace"), { recursive: true });
  writeFileSync(join(root, "docs", "qa", "slice-report-latest.md"), `${md}\n`);
  writeFileSync(join(root, "trace", "slice-report-latest.json"), `${JSON.stringify(result, null, 2)}\n`);
}
console.log(md);
process.exit(Object.values(commands).some((c) => c.exitCode !== 0) ? 1 : 0);
